INSERT INTO Extras (Name, Description) VALUES ('Rustproofing','Extra protection from rust');
INSERT INTO Extras (Name, Description) VALUES ('Fabric protection','Spray coating to protect fabric and leather interiors');
INSERT INTO Extras (Name, Description) VALUES ('Extended warranty','A longer warranty period');
INSERT INTO Extras (Name, Description) VALUES ('Paint protection','A protective coating for the car exterior');
INSERT INTO Extras (Name, Description) VALUES ('Anti-lock braking system (ABS)','Automatically pumps brakes to prevent them from locking up');
INSERT INTO Extras (Name, Description) VALUES ('Bluetooth integration','Wireless hands-free mobile phone integration');
INSERT INTO Extras (Name, Description) VALUES ('GPS or satellite navigation','An electronic map that uses satellite and GPS data');
INSERT INTO Extras (Name, Description) VALUES ('Prepaid maintenance plans','Pay for your future car maintenance in advance');
INSERT INTO Extras (Name, Description) VALUES ('Bull bars or nudge bars','Protective bars for the front and/or rear of the car');
INSERT INTO Extras (Name, Description) VALUES ('Extra airbags','Extra airbags for the sides, passenger seats and elsewhere');
INSERT INTO Extras (Name, Description) VALUES ('Rear view camera','Rear view camera for reversing and parking');
INSERT INTO Extras (Name, Description) VALUES ('Extra tinting','Bonus tinting to darken the windows and keep the interior cooler');
INSERT INTO Extras (Name, Description) VALUES ('Headlight protectors','Covers to protect the headlights');
INSERT INTO Extras (Name, Description) VALUES ('Floor mats','Floor mats for your car');
INSERT INTO Extras (Name, Description) VALUES ('Roof racks','Roof-mounted luggage racks');
INSERT INTO Extras (Name, Description) VALUES ('Special suspension','Modified non-standard suspension');
INSERT INTO Extras (Name, Description) VALUES ('VIN etching','Vehicle ID numbers etched onto the windows (makes the car a considerably less tempting target for theft)');
INSERT INTO Extras (Name, Description) VALUES ('Car alarm installation','A car alarm or an extra alarm');
INSERT INTO Extras (Name, Description) VALUES ('Premium sound system','A higher quality sound system than the default model');
INSERT INTO Extras (Name, Description) VALUES ('Towbar','A rear-mounted bar for towing');
INSERT INTO Extras (Name, Description) VALUES ('Ceramic brake pads','Advanced, durable and heat-resistant brake pads');
INSERT INTO Extras (Name, Description) VALUES ('Colour stitching','Different colour thread used for the stitching and the seats (a purely cosmetic extra)');
INSERT INTO Extras (Name, Description) VALUES ('Aux connection','Now a fairly standard feature that lets you connect your phone or MP3 player with an aux cord');
INSERT INTO Extras (Name, Description) VALUES ('Heated seats','Heating systems inside the seats');
INSERT INTO Extras (Name, Description) VALUES ('Audible reverse sensors','Audible warning system indicating how much room you have behind the car');
INSERT INTO Extras (Name, Description) VALUES ('Bundled insurance','Added insurance policies, such as life or car insurance, often thrown in with car loans or new vehicles');
INSERT INTO Extras (Name, Description) VALUES ('Panoramic sunroof','A larger sunroof for more light and scenery');
INSERT INTO Extras (Name, Description) VALUES ('Adaptive cruise control','Advanced cruise control that can adjust speed to match traffic');
INSERT INTO Extras (Name, Description) VALUES ('Nitrogen inflation','Extra nitrogen in your car tires for improved performance');
